nguage: cpp
osx_image: xcode12.2

compiler:
- clang

os:
- osx

addons:
    homebrew:
        packages:
        - cmake
        update: true

before_script:
- mkdir -p build && cd build
- cmake -DCI=True ..

script:
- cd build
- cmake --build .
- ctest

